Repository codesquad-member-2020/baseball-09, pull requests merged in 2020-05, with the labels that each got.

#8 [FE] 프로젝트 환경설정
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
  FE/.gitignore
  FE/babel.config.js
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/index.tsx
  FE/tsconfig.json
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: Feature, fe

#12 [FE] 메인 화면 컴포넌트 작성
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/MainPage/GameSelectMenu/GameDisplay/GameDisplay.tsx
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/components/MainPage/bench-clearing.jpg
  FE/tsconfig.json
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: Feature, fe

#13 [FE] 메인 화면 - 데이터, 모델 생성
  .github/ISSUE_TEMPLATE/-fe--title.md
  FE/src/models/gameList.ts
  FE/src/models/gameListData.ts
Labels: Feature, fe

#17 [FE] 라우팅 작업
  FE/.gitignore
  FE/img.d.ts
  FE/src/App.tsx
  FE/src/components/ErrorPage/ErrorPage.tsx
  FE/src/components/ErrorPage/TrapCard.jpg
  FE/webpack.dev.js
Labels: Feature, fe

#18 [FE] 메인화면 - 목데이터로 렌더링되게 변경
  FE/.gitignore
  FE/src/components/MainPage/GameSelectMenu/GameDisplay/GameDisplay.tsx
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/models/gameList.ts
Labels: Feature, fe

#19 [FE] 환경설정 & 시작 화면 리뷰 요청
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  FE/.gitignore
  FE/babel.config.js
  FE/img.d.ts
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/ErrorPage/ErrorPage.tsx
  FE/src/components/ErrorPage/TrapCard.jpg
  FE/src/components/MainPage/GameSelectMenu/GameDisplay/GameDisplay.tsx
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/components/MainPage/bench-clearing.jpg
  FE/src/index.tsx
  FE/src/models/gameList.ts
  FE/src/models/gameListData.ts
  FE/tsconfig.json
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
  FE/yarn.lock
Labels: fe, fe-review

#20 [iOS] 게임 선택화면 UI 구성
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.pbxproj
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcuserdata/limwin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/BaseBallApp/BaseBallApp.xcodeproj/xcuserdata/limwin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/BaseBallApp/BaseBallApp/AppDelegate.swift
  iOS/BaseBallApp/BaseBallApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/BaseBallApp/BaseBallApp/Assets.xcassets/Contents.json
  iOS/BaseBallApp/BaseBallApp/Base.lproj/LaunchScreen.storyboard
  iOS/BaseBallApp/BaseBallApp/Base.lproj/Main.storyboard
  iOS/BaseBallApp/BaseBallApp/Controller/GameTabController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/TeamSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Info.plist
  iOS/BaseBallApp/BaseBallApp/Model/DataManager.swift
  iOS/BaseBallApp/BaseBallApp/SceneDelegate.swift
  iOS/BaseBallApp/BaseBallApp/View/GameSelectView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameSelectView.xib
Labels: iOS

#26 [FE] 참가 가능 여부 처리
  FE/src/components/MainPage/GameSelectMenu/GameDisplay/GameDisplay.tsx
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
Labels: Feature, fe

#30 Mock data
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/baseball09/Baseball09Application.java
  BE/src/main/java/com/codesquad/baseball09/config/Swagger2Configure.java
  BE/src/main/java/com/codesquad/baseball09/config/WebConfig.java
  BE/src/main/java/com/codesquad/baseball09/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball09/controller/HealthCheckRestController.java
  BE/src/main/java/com/codesquad/baseball09/model/BatterLog.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailPlayer.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Game.java
  BE/src/main/java/com/codesquad/baseball09/model/InningScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Match.java
  BE/src/main/java/com/codesquad/baseball09/model/Pitch.java
  BE/src/main/java/com/codesquad/baseball09/model/Player.java
  BE/src/main/java/com/codesquad/baseball09/model/PlayerList.java
  BE/src/main/java/com/codesquad/baseball09/model/State.java
  BE/src/main/java/com/codesquad/baseball09/model/Team.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseball09/Baseball09ApplicationTests.java
Labels: be

#31 [FE] 게임 화면 작성
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/GamePage/CurrentTurn/CurrentTurn.tsx
  FE/src/components/GamePage/GamePage.tsx
  FE/src/components/GamePage/PlayerInfo/Info/Info.tsx
  FE/src/components/GamePage/PlayerInfo/PlayerInfo.tsx
  FE/src/components/GamePage/ScoreBoard/ScoreBoard.tsx
  FE/src/components/MainPage/GameSelectMenu/GameDisplay/GameDisplay.tsx
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/components/MainPage/main-bgm.mp3
  FE/tsconfig.json
Labels: enhancement, fe

#33 [iOS] 팀 선택화면 UI 구성
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.pbxproj
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcuserdata/limwin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/BaseBallApp/BaseBallApp/Assets.xcassets/ButtonColor.colorset/Contents.json
  iOS/BaseBallApp/BaseBallApp/Base.lproj/Main.storyboard
  iOS/BaseBallApp/BaseBallApp/Controller/GameSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/GameTabController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/TeamSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Model/DataManager.swift
  iOS/BaseBallApp/BaseBallApp/View/TeamSelectButton.swift
Labels: iOS

#35 [FE] 야구 필드 화면 구성
  FE/src/components/GamePage/BaseballField/BaseballField.tsx
  FE/src/components/GamePage/BaseballField/CurrentInfo/CurrentInfo.tsx
  FE/src/components/GamePage/BaseballField/Field/Field.tsx
  FE/src/components/GamePage/BaseballField/Field/fitcher.png
  FE/src/components/GamePage/BaseballField/Field/hitter.png
  FE/src/components/GamePage/BaseballField/field.png
  FE/src/components/GamePage/GamePage.tsx
Labels: Feature, fe

#41 [iOS] 게임화면 스켈레톤 UI 구성
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.pbxproj
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcuserdata/limwin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/BaseBallApp/BaseBallApp/Base.lproj/Main.storyboard
  iOS/BaseBallApp/BaseBallApp/Controller/GameSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/GameViewController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/TeamSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/CurrentPlayerCell.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameLogCell.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/CircleView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/GameProgressView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/GameScreenView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/PitchingResult.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/PitchingResult.xib
  iOS/BaseBallApp/BaseBallApp/View/GameView/TeamScoreView.swift
  iOS/BaseBallApp/BaseBallApp/View/MainView/GameSelectView.swift
  iOS/BaseBallApp/BaseBallApp/View/MainView/GameSelectView.xib
  iOS/BaseBallApp/BaseBallApp/View/MainView/TeamSelectButton.swift
Labels: iOS

#45 Dev be
  BE/src/main/java/com/codesquad/baseball09/config/Swagger2Config.java
  BE/src/main/java/com/codesquad/baseball09/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball09/model/Match.java
  BE/src/main/java/com/codesquad/baseball09/model/api/ApiError.java
  BE/src/main/java/com/codesquad/baseball09/model/api/ApiResult.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/GameRequest.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/TeamRequest.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/TeamResponse.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: be

#40 Testing
  FE/babel.config.js
  FE/jest-dom.d.ts
  FE/jest.config.js
  FE/package.json
  FE/src/components/ErrorPage/ErrorPage.tsx
  FE/test/ErrorPage.test.tsx
  FE/tsconfig.json
  FE/yarn.lock
Labels: fe

#39 [FE] 야구 필드 애니메이션 적용
  FE/src/components/GamePage/BaseballField/BaseballField.tsx
  FE/src/components/GamePage/BaseballField/Field/Field.tsx
  FE/src/components/GamePage/BaseballField/Field/Hitter/Hitter.tsx
  FE/src/components/GamePage/BaseballField/Field/Hitter/hitter.png
  FE/src/components/GamePage/BaseballField/Field/pitcher.png
Labels: Feature, fe

#47 Feature be main page
  BE/src/main/java/com/codesquad/baseball09/controller/GameRestController.java
  BE/src/main/java/com/codesquad/baseball09/controller/GeneralExceptionHandler.java
  BE/src/main/java/com/codesquad/baseball09/error/AlreadySelectedException.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/Match.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/TeamResponse.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
Labels: be

#48 Dev be
  BE/src/main/java/com/codesquad/baseball09/controller/GameRestController.java
  BE/src/main/java/com/codesquad/baseball09/controller/GeneralExceptionHandler.java
  BE/src/main/java/com/codesquad/baseball09/error/AlreadySelectedException.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/Match.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/TeamResponse.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
Labels: be

#49 Testing
  FE/src/App.tsx
  FE/src/components/GamePage/BaseballField/BaseballField.tsx
  FE/src/components/GamePage/BaseballField/CurrentInfo/CurrentInfo.tsx
  FE/src/components/GamePage/BaseballField/Field/Field.tsx
  FE/src/components/GamePage/BaseballField/Field/Hitter/Hitter.tsx
  FE/src/components/GamePage/CurrentTurn/CurrentTurn.tsx
  FE/src/components/GamePage/GamePage.tsx
  FE/src/components/GamePage/PlayerInfo/Info/Info.tsx
  FE/src/components/GamePage/PlayerInfo/PlayerInfo.tsx
  FE/src/components/GamePage/ScoreBoard/ScoreBoard.tsx
  FE/src/components/MainPage/GameSelectMenu/GameDisplay/GameDisplay.tsx
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/theme/theme.ts
  FE/test/ErrorPage.test.tsx
  FE/tsconfig.json
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: Feature, fe

#50 [FE] 선수 명단 페이지 구성
  FE/src/components/PlayerListPage/PlayerInfoList/PlayerInfoList.tsx
  FE/src/components/PlayerListPage/PlayerListPage.tsx
  FE/src/models/playerList.ts
  FE/src/models/playerListData.ts
Labels: Feature, fe

#56 Feature be game page
  BE/src/main/java/com/codesquad/baseball09/controller/GameRestController.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailPlayer.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Game.java
  BE/src/main/java/com/codesquad/baseball09/model/InningScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Match.java
  BE/src/main/java/com/codesquad/baseball09/model/Pitch.java
  BE/src/main/java/com/codesquad/baseball09/model/Player.java
  BE/src/main/java/com/codesquad/baseball09/model/PlayerList.java
  BE/src/main/java/com/codesquad/baseball09/model/SBO.java
  BE/src/main/java/com/codesquad/baseball09/model/Score.java
  BE/src/main/java/com/codesquad/baseball09/model/State.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/GameRequest.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/GameResponse.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/TeamResponse.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: be

#60 Dev be
  BE/src/main/java/com/codesquad/baseball09/controller/GameRestController.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailPlayer.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Game.java
  BE/src/main/java/com/codesquad/baseball09/model/InningScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Match.java
  BE/src/main/java/com/codesquad/baseball09/model/Pitch.java
  BE/src/main/java/com/codesquad/baseball09/model/Player.java
  BE/src/main/java/com/codesquad/baseball09/model/PlayerList.java
  BE/src/main/java/com/codesquad/baseball09/model/SBO.java
  BE/src/main/java/com/codesquad/baseball09/model/Score.java
  BE/src/main/java/com/codesquad/baseball09/model/State.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/GameRequest.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/GameResponse.java
  BE/src/main/java/com/codesquad/baseball09/model/api/response/TeamResponse.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: be

#55 [FE] 서버와 통신하기
  FE/package.json
  FE/src/components/MainPage/GameSelectMenu/GameSelectMenu.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/customHooks/useFetch.tsx
  FE/yarn.lock
Labels: Feature, fe

#67 Feature be game page
  BE/build.gradle
  BE/src/main/java/com/codesquad/baseball09/config/Swagger2Config.java
  BE/src/main/java/com/codesquad/baseball09/controller/GameRestController.java
  BE/src/main/java/com/codesquad/baseball09/model/BatterLog.java
  BE/src/main/java/com/codesquad/baseball09/model/BattingLog.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailPlayer.java
  BE/src/main/java/com/codesquad/baseball09/model/InningStatus.java
  BE/src/main/java/com/codesquad/baseball09/model/Pitch.java
  BE/src/main/java/com/codesquad/baseball09/model/SBO.java
  BE/src/main/java/com/codesquad/baseball09/model/State.java
  BE/src/main/java/com/codesquad/baseball09/model/Status.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/BattingLogRequest.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/PitchRequest.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: be

#66 [FE] 선수 명단, 게임 보드 - 상태관리 작성
  FE/src/App.tsx
  FE/src/actions/gameBoardAction.tsx
  FE/src/actions/playerAction.tsx
  FE/src/components/MainPage/MainPage.tsx
  FE/src/contexts/gameBoardContext.tsx
  FE/src/contexts/playerContext.tsx
  FE/src/customHooks/useMyContext.tsx
  FE/src/models/gameBoard.ts
  FE/src/models/playerList.ts
  FE/src/models/playerListData.ts
  FE/src/provider/Provider.tsx
  FE/src/reducers/gameBoardReducer.ts
  FE/src/reducers/playerReducer.ts
Labels: Feature, fe

#68 [iOS] 네트워크 통신 기능 구현
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.pbxproj
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcuserdata/limwin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/BaseBallApp/BaseBallApp/Base.lproj/Main.storyboard
  iOS/BaseBallApp/BaseBallApp/Controller/GameSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/GameViewController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/TeamSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Info.plist
  iOS/BaseBallApp/BaseBallApp/Model/DataManager.swift
  iOS/BaseBallApp/BaseBallApp/Model/GameProgressInfo.swift
  iOS/BaseBallApp/BaseBallApp/Model/MainGameList.swift
  iOS/BaseBallApp/BaseBallApp/Model/PitchingResult.swift
  iOS/BaseBallApp/BaseBallApp/Model/TeamSelectResult.swift
  iOS/BaseBallApp/BaseBallApp/Util/DataUseCase.swift
  iOS/BaseBallApp/BaseBallApp/Util/NetworkManager.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/CurrentPlayerCell.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/CurrentPlayerView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/CircleView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/GameProgressView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/GameScreenTotalView.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/PitchingResult.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameScreen/PitchingResult.xib
  iOS/BaseBallApp/BaseBallApp/View/GameView/PtichButton.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/CurrentPlayerViewModel.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/GameInfoViewModel.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/GameScoreViewModel.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/GameSelectViewModel.swift
Labels: iOS

#71 Feature be refactor main
  BE/src/main/java/com/codesquad/baseball09/controller/HealthCheckRestController.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Game.java
  BE/src/main/java/com/codesquad/baseball09/model/InningStatus.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/PitchRequest.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: be

#72 Dev be
  BE/build.gradle
  BE/src/main/java/com/codesquad/baseball09/config/Swagger2Config.java
  BE/src/main/java/com/codesquad/baseball09/controller/GameRestController.java
  BE/src/main/java/com/codesquad/baseball09/controller/HealthCheckRestController.java
  BE/src/main/java/com/codesquad/baseball09/model/BatterLog.java
  BE/src/main/java/com/codesquad/baseball09/model/BattingLog.java
  BE/src/main/java/com/codesquad/baseball09/model/Board.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailPlayer.java
  BE/src/main/java/com/codesquad/baseball09/model/DetailScore.java
  BE/src/main/java/com/codesquad/baseball09/model/Game.java
  BE/src/main/java/com/codesquad/baseball09/model/InningStatus.java
  BE/src/main/java/com/codesquad/baseball09/model/Pitch.java
  BE/src/main/java/com/codesquad/baseball09/model/SBO.java
  BE/src/main/java/com/codesquad/baseball09/model/State.java
  BE/src/main/java/com/codesquad/baseball09/model/Status.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/BattingLogRequest.java
  BE/src/main/java/com/codesquad/baseball09/model/api/request/PitchRequest.java
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: be

#74 Fix : MySQL 오류
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/resources/schema.sql
Labels: be

#75 fix : SQL 오류 수정, player 데이터 추가, game 데이터 미리 생성
  BE/src/main/java/com/codesquad/baseball09/repository/GameRepository.java
  BE/src/main/java/com/codesquad/baseball09/repository/JdbcGameRepository.java
  BE/src/main/java/com/codesquad/baseball09/service/GameService.java
  BE/src/main/resources/data.sql
Labels: be

#76 [iOS] 게임화면 기능 구현
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.pbxproj
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcuserdata/limwin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/BaseBallApp/BaseBallApp.xcodeproj/xcuserdata/limwin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  iOS/BaseBallApp/BaseBallApp/Base.lproj/Main.storyboard
  iOS/BaseBallApp/BaseBallApp/Controller/GameViewController.swift
  iOS/BaseBallApp/BaseBallApp/Controller/TeamSelectViewController.swift
  iOS/BaseBallApp/BaseBallApp/Model/CurrentBatterInfo.swift
  iOS/BaseBallApp/BaseBallApp/Model/GameProgressInfo.swift
  iOS/BaseBallApp/BaseBallApp/Model/PostGameStart.swift
  iOS/BaseBallApp/BaseBallApp/Util/DataUseCase.swift
  iOS/BaseBallApp/BaseBallApp/View/GameView/GameTableViewDataSource.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/CurrentPitchLogViewModel.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/GameInfoViewModel.swift
  iOS/BaseBallApp/BaseBallApp/ViewModel/GameScoreViewModel.swift
Labels: iOS

#78 github 로그인 기능 추가
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.pbxproj
  iOS/BaseBallApp/BaseBallApp.xcodeproj/project.xcworkspace/xcuserdata/limwin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/BaseBallApp/BaseBallApp/Base.lproj/Main.storyboard
  iOS/BaseBallApp/BaseBallApp/Controller/LoginViewConrtoller.swift
  iOS/BaseBallApp/BaseBallApp/Info.plist
  iOS/BaseBallApp/BaseBallApp/Model/TokenManager.swift
  iOS/BaseBallApp/BaseBallApp/Util/DataUseCase.swift
  iOS/BaseBallApp/BaseBallApp/Util/NetworkManager.swift
Labels: iOS
